# Generated by Django 3.1.4 on 2021-06-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_quantity', models.IntegerField()),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_quantity', models.IntegerField()),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change', models.DecimalField(decimal_places=2, max_digits=7)),
                ('change_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
    ]
